"use client";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <>
      <Head>
        <title>My first app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Home Page</h1>
        <p>{count}</p>
        <button onClick={() => setCount(count + 1)}>Click me</button>
      </main>
    </>
  );
}
